# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c441527746c047ba0aedeba0893a37e21d09e5315d69ca7df69b036001c6d6c596d985bf5ce0250651a2f33c2a939339692e0064d13890d9bf6e756d36335e

test:
  secret_key_base: ab060afd955a06b723a2999e5731349487d85d498c0b2ca491f0c666e10354f1794642c5e7852ca7504c45ccae2d55de0f2e74c17608b16b05e257395666786e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
